language: node_js
node_js:
  - "9.5.0"
install:
  - yarn
script:
  - yarn prod
env:
  global:
    - secure: tmhKDxxhLACHONPciiPYAVW3BBOziuwUzi465gvTKb5knQeKNykiQ6GQaGhwzTrTPZjWJMGjLXDZ7ftflD7BH51pR+QpHQDs4iLeQhGVscuZ1XyW8EoJbQIBPx94RQqUMVh6Osq3sTXXvOoPWNsF+HbazdiriHVcLCUkcg9hN3e9CkrGB1/Zggk/1GT7F2G8+uBI7cKw3wdjiq7twndyUl1n6Ta+QPhxdPchuyjOi5WtRnHtkicNIHLnuB466jsZGdHVfFJgAlud7FRFvmKQ4ve2X/Y0519JGg8Jy+IvJVVl3Ika9D/ZMcFI47i0XG5MFfE9nwmmQiNDSoYrGbjuYyMhN3fzG5ZcyKIU6rfrKq9X8q7jFwNW/wZtKoV4Q0HuRlK4smL25pkarTgcRS7a6ZP+ixmFHeQLQqRAKaqzIPxMNfMHRtMF2kzLO0736Wrafty80h5grYCA65Sqq/L2OzoDiglYBqsW34AwzmnfERDq3Jd08/S0vJgLQwvZqDxxACufsnOkp8ZZY99TnPeJq7kjwrFuiHd/B5aqcaPM+K7m3sA5kxPFfHgRT4r6HigQibjW7VFL9JHirzLzHA2kdIa4TlAnfEbk3TzM89dwfEfG1xE0RMBR1BUEh2GPPpbmG4v1Ta0c18DYKxm7EvrOtWJPejT0XeY0Ihgbf2qbL4s=
    - secure: YGCgoaP9Vfhd4Z8B7qukF06n480o6l+pqJd95ZC1l7NzSKIMFAIQ8LuqmBZwcPFj27LsIFhOHE8ItB3IfDeQZKnW68JJMche+CPGed30D5t8SXDEKaKYXk09mQMQg/hJ3beUdFRwYq6p2gKt/gb/SJBwUnAD0IztRCjpYWcoKoapBjoPUHdB1hBbic33ziVtKcMBJ75oIHe6EHGAvvw3JGvK+OcI3EDVOd/6uesjX/5EPSc3PUZJbJ+9e9+S4LFpZppSvQhkHjGruM2uEpM0TEKwvmNtyBApq7U2BrKwBkh46bhRezfmyXHCacbhUuAW3wdzdc6LSSACLiwggJ/FLOjZBOOF9kh9fm07WpVysE3VoJKJVhsq5mZG4m26oc9qLMeCpTAAl0lxmq724o/TfLRSsfLGgGQSmXMD4sf29YuqxUK93NVGXcCIjBanXyij+op7eebayKm5zny4H1pS+IhK/O6lhUomGnOHvqg68YCIfc7gC5SXzc6AbsJU1l6JLZY3ETBkJfkFv+UzOxdL1Vz0qxG40jUMGvtZJFjFC+Ejv9DlGr1oz2oa69yzubz8n5EcHfJkL413VHUt+8riwl1KaMOaVr/zmU9bsSBTCj4SmaOkBbFXyaJra4VymbycHlx1KDorCovhxFgf2PIBOaX4dNmYK9eh++TwF60x1NU=
after_success:
  gulp deploy --user $FTP_USER --password $FTP_PASSWORD
